### ISSUE TITLE
Error api?

### ISSUE THREAD

**Issue by Venorg** [abdozmantar/StableDiffusion-InstaSwap#1]
[error.txt](https://github.com/user-attachments/files/17270648/error.txt)
Get this error messages on launcg forge. This happens only with instaswap extension

**Comment by abdozmantar** [comment]
**Issue Resolution Steps:**

The issue is related to the version of the **albumentations** package. To fix this error, please follow the steps below:

1. First, you'll need to use the **Python** from your virtual environment to install the required version of the package. Open your terminal and run the following command:

   - If your virtual environment is located in the `stable-diffusion-webui\venv\Scripts` folder, use this command to install the correct version of the package:
     ```bash
     <path_to_stable_diffusion_webui>\venv\Scripts\python -m pip install albumentations==1.4.3
     ```

   **Note:** Replace `<path_to_stable_diffusion_webui>` with the path where the **stable-diffusion-webui** folder is located on your system (e.g., `C:\Users\YourUsername\Desktop` on Windows).

2. After installing the package, go to the **UI** and click the **"Apply and Restart UI"** button to reload the extension and apply the changes.

This should resolve the error related to the **albumentations** package. If you encounter any further issues, feel free to reach out! 😊
